participants:

    Solid:
        interfaces:
        - nodes-mesh: Solid-Mesh
          patch: CHTnodes
          read-data: [Temperature]
          write-data: [Heat-Flux]
          
precice-config-file: ../precice-config.xml
